name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.8.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/arabic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
    - family: Noor
      fonts:
        - asset: assets/fonts/noorehira.ttf
    - family: Nilofar
      fonts:
        - asset: assets/fonts/nilofar.ttf
  
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
